// Mock data for development - replace with Contentstack API calls
import { Book, Category, Banner, Author } from './types';

export const mockAuthors: Author[] = [
  {
    uid: 'author-1',
    title: 'Morgan Housel',
    name: 'Morgan Housel',
    slug: 'morgan-housel',
    bio: 'Morgan Housel is a partner at The Collaborative Fund and a former columnist at The Motley Fool and The Wall Street Journal.',
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'author-2',
    title: 'Hector Garcia',
    name: 'Hector Garcia',
    slug: 'hector-garcia',
    bio: 'Hector Garcia is a citizen of Japan, where he has lived for over a decade.',
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'author-3',
    title: 'Chetan Bhagat',
    name: 'Chetan Bhagat',
    slug: 'chetan-bhagat',
    bio: 'Chetan Bhagat is an Indian author, columnist, and screenwriter.',
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'author-4',
    title: 'J.K. Rowling',
    name: 'J.K. Rowling',
    slug: 'jk-rowling',
    bio: 'J.K. Rowling is a British author and philanthropist, best known for the Harry Potter series.',
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'author-5',
    title: 'Rick Riordan',
    name: 'Rick Riordan',
    slug: 'rick-riordan',
    bio: 'Rick Riordan is an American author known for the Percy Jackson series.',
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
];

export const mockCategories: Category[] = [
  {
    uid: 'cat-1',
    title: 'Fiction',
    name: 'Fiction',
    slug: 'fiction',
    description: 'Explore worlds beyond imagination',
    color: '#e87523',
    is_featured: true,
    display_order: 1,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'cat-2',
    title: 'Non-Fiction',
    name: 'Non-Fiction',
    slug: 'non-fiction',
    description: 'Real stories, real insights',
    color: '#577ca2',
    is_featured: true,
    display_order: 2,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'cat-3',
    title: 'Self-Help',
    name: 'Self-Help',
    slug: 'self-help',
    description: 'Transform your life',
    color: '#d946ef',
    is_featured: true,
    display_order: 3,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'cat-4',
    title: 'Business & Finance',
    name: 'Business & Finance',
    slug: 'business-finance',
    description: 'Master the art of wealth',
    color: '#059669',
    is_featured: true,
    display_order: 4,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'cat-5',
    title: 'Mystery & Thriller',
    name: 'Mystery & Thriller',
    slug: 'mystery-thriller',
    description: 'Edge-of-your-seat suspense',
    color: '#dc2626',
    is_featured: true,
    display_order: 5,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'cat-6',
    title: 'Kids Books',
    name: 'Kids Books',
    slug: 'kids-books',
    description: 'Adventures for young minds',
    color: '#f59e0b',
    is_featured: true,
    display_order: 6,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'cat-7',
    title: 'Romance',
    name: 'Romance',
    slug: 'romance',
    description: 'Love stories that touch the heart',
    color: '#ec4899',
    is_featured: true,
    display_order: 7,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'cat-8',
    title: 'Fantasy & Adventure',
    name: 'Fantasy & Adventure',
    slug: 'fantasy-adventure',
    description: 'Epic journeys await',
    color: '#8b5cf6',
    is_featured: true,
    display_order: 8,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
];

export const mockBooks: Book[] = [
  {
    uid: 'book-1',
    title: 'The Psychology of Money',
    slug: 'psychology-of-money',
    author: mockAuthors[0],
    description: 'Timeless lessons on wealth, greed, and happiness. Doing well with money isn\'t necessarily about what you know. It\'s about how you behave.',
    short_description: 'Timeless lessons on wealth, greed, and happiness',
    cover_image: {
      uid: 'img-1',
      url: 'https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=400&h=600&fit=crop',
      filename: 'psychology-of-money.jpg',
      content_type: 'image/jpeg',
    },
    price: 339,
    original_price: 399,
    discount_percentage: 15,
    isbn: '978-0857197689',
    publisher: 'Harriman House',
    pages: 256,
    language: 'English',
    format: 'paperback',
    category: mockCategories[3],
    rating: 4.8,
    review_count: 15420,
    is_bestseller: true,
    is_featured: true,
    stock_quantity: 50,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'book-2',
    title: 'Ikigai: The Japanese Secret to a Long and Happy Life',
    slug: 'ikigai',
    author: mockAuthors[1],
    description: 'The people of Japan believe that everyone has an ikigai – a reason to jump out of bed each morning. This book reveals the secrets to their philosophy for a happy life.',
    short_description: 'The Japanese secret to a long and happy life',
    cover_image: {
      uid: 'img-2',
      url: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop',
      filename: 'ikigai.jpg',
      content_type: 'image/jpeg',
    },
    price: 509,
    original_price: 599,
    discount_percentage: 15,
    isbn: '978-0143130727',
    publisher: 'Penguin Books',
    pages: 208,
    language: 'English',
    format: 'hardcover',
    category: mockCategories[2],
    rating: 4.6,
    review_count: 8932,
    is_bestseller: true,
    is_featured: true,
    stock_quantity: 35,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'book-3',
    title: '12 Years: My Messed-Up Love Story',
    slug: '12-years-love-story',
    author: mockAuthors[2],
    description: 'A heartwarming tale of love, loss, and the complexities of relationships in modern India.',
    short_description: 'A modern Indian love story',
    cover_image: {
      uid: 'img-3',
      url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop',
      filename: '12-years.jpg',
      content_type: 'image/jpeg',
    },
    price: 339,
    original_price: 399,
    discount_percentage: 15,
    isbn: '978-9356294721',
    publisher: 'Westland',
    pages: 320,
    language: 'English',
    format: 'paperback',
    category: mockCategories[6],
    rating: 4.2,
    review_count: 5621,
    is_bestseller: true,
    stock_quantity: 45,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'book-4',
    title: 'Harry Potter and the Deathly Hallows',
    slug: 'harry-potter-deathly-hallows',
    author: mockAuthors[3],
    description: 'The final adventure in the Harry Potter series. Harry must find and destroy the remaining Horcruxes to defeat Lord Voldemort once and for all.',
    short_description: 'The epic conclusion to the Harry Potter saga',
    cover_image: {
      uid: 'img-4',
      url: 'https://images.unsplash.com/photo-1618666012174-83b441c0bc76?w=400&h=600&fit=crop',
      filename: 'harry-potter-7.jpg',
      content_type: 'image/jpeg',
    },
    price: 679,
    original_price: 799,
    discount_percentage: 15,
    isbn: '978-1408855713',
    publisher: 'Bloomsbury',
    pages: 640,
    language: 'English',
    format: 'paperback',
    category: mockCategories[5],
    age_group: '9-12 Years',
    rating: 4.9,
    review_count: 28453,
    is_bestseller: true,
    is_featured: true,
    stock_quantity: 60,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'book-5',
    title: 'Percy Jackson: The Last Olympian',
    slug: 'percy-jackson-last-olympian',
    author: mockAuthors[4],
    description: 'The final book in the Percy Jackson series. Percy faces the war against the Titans and must make crucial decisions about his destiny.',
    short_description: 'The thrilling conclusion to Percy Jackson\'s story',
    cover_image: {
      uid: 'img-5',
      url: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=600&fit=crop',
      filename: 'percy-jackson-5.jpg',
      content_type: 'image/jpeg',
    },
    price: 382,
    original_price: 450,
    discount_percentage: 15,
    isbn: '978-0141346885',
    publisher: 'Puffin Books',
    pages: 381,
    language: 'English',
    format: 'paperback',
    category: mockCategories[5],
    age_group: '9-12 Years',
    rating: 4.7,
    review_count: 12890,
    is_bestseller: true,
    stock_quantity: 40,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'book-6',
    title: 'The Art of Spending Money',
    slug: 'art-of-spending-money',
    author: mockAuthors[0],
    description: 'Morgan Housel explores the psychology behind how we spend, save, and think about money.',
    short_description: 'Understanding your relationship with money',
    cover_image: {
      uid: 'img-6',
      url: 'https://images.unsplash.com/photo-1554672723-d42a16e533db?w=400&h=600&fit=crop',
      filename: 'art-of-spending.jpg',
      content_type: 'image/jpeg',
    },
    price: 424,
    original_price: 499,
    discount_percentage: 15,
    isbn: '978-0857199096',
    publisher: 'Harriman House',
    pages: 192,
    language: 'English',
    format: 'hardcover',
    category: mockCategories[3],
    rating: 4.5,
    review_count: 3240,
    is_bestseller: true,
    is_new_arrival: true,
    stock_quantity: 30,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'book-7',
    title: 'Atomic Habits',
    slug: 'atomic-habits',
    author: {
      uid: 'author-6',
      title: 'James Clear',
      name: 'James Clear',
      slug: 'james-clear',
      bio: 'James Clear is an author and speaker focused on habits and continuous improvement.',
      created_at: '2024-01-01',
      updated_at: '2024-01-01',
      locale: 'en-us',
    },
    description: 'Transform your life with tiny changes. An easy and proven way to build good habits and break bad ones.',
    short_description: 'Tiny changes, remarkable results',
    cover_image: {
      uid: 'img-7',
      url: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&h=600&fit=crop',
      filename: 'atomic-habits.jpg',
      content_type: 'image/jpeg',
    },
    price: 509,
    original_price: 599,
    discount_percentage: 15,
    isbn: '978-0735211292',
    publisher: 'Penguin Random House',
    pages: 320,
    language: 'English',
    format: 'hardcover',
    category: mockCategories[2],
    rating: 4.9,
    review_count: 45230,
    is_bestseller: true,
    is_featured: true,
    stock_quantity: 55,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'book-8',
    title: 'The Secret of Secrets',
    slug: 'secret-of-secrets',
    author: {
      uid: 'author-7',
      title: 'Dan Brown',
      name: 'Dan Brown',
      slug: 'dan-brown',
      bio: 'Dan Brown is an American author best known for his thriller novels.',
      created_at: '2024-01-01',
      updated_at: '2024-01-01',
      locale: 'en-us',
    },
    description: 'A heart-pounding thriller that takes you through ancient mysteries and modern conspiracies.',
    short_description: 'A gripping new thriller from the master of suspense',
    cover_image: {
      uid: 'img-8',
      url: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop',
      filename: 'secret-of-secrets.jpg',
      content_type: 'image/jpeg',
    },
    price: 1274,
    original_price: 1499,
    discount_percentage: 15,
    isbn: '978-0593731451',
    publisher: 'Doubleday',
    pages: 448,
    language: 'English',
    format: 'hardcover',
    category: mockCategories[4],
    rating: 4.4,
    review_count: 8920,
    is_bestseller: true,
    is_new_arrival: true,
    stock_quantity: 25,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'book-9',
    title: 'The Magic of the Lost Story',
    slug: 'magic-lost-story',
    author: {
      uid: 'author-8',
      title: 'Sudha Murty',
      name: 'Sudha Murty',
      slug: 'sudha-murty',
      bio: 'Sudha Murty is an Indian author and philanthropist.',
      created_at: '2024-01-01',
      updated_at: '2024-01-01',
      locale: 'en-us',
    },
    description: 'A magical tale for children about the power of stories and imagination.',
    short_description: 'A magical tale for young readers',
    cover_image: {
      uid: 'img-9',
      url: 'https://images.unsplash.com/photo-1535905557558-afc4877a26fc?w=400&h=600&fit=crop',
      filename: 'magic-lost-story.jpg',
      content_type: 'image/jpeg',
    },
    price: 233,
    original_price: 275,
    discount_percentage: 15,
    isbn: '978-0143455820',
    publisher: 'Puffin India',
    pages: 160,
    language: 'English',
    format: 'paperback',
    category: mockCategories[5],
    age_group: '6-8 Years',
    rating: 4.8,
    review_count: 2156,
    is_bestseller: true,
    stock_quantity: 35,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'book-10',
    title: 'The Midnight Library',
    slug: 'midnight-library',
    author: {
      uid: 'author-9',
      title: 'Matt Haig',
      name: 'Matt Haig',
      slug: 'matt-haig',
      bio: 'Matt Haig is a British author known for his novels and books on mental health.',
      created_at: '2024-01-01',
      updated_at: '2024-01-01',
      locale: 'en-us',
    },
    description: 'Between life and death there is a library filled with books about all the lives you could have lived.',
    short_description: 'A novel about all the lives we could have lived',
    cover_image: {
      uid: 'img-10',
      url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
      filename: 'midnight-library.jpg',
      content_type: 'image/jpeg',
    },
    price: 424,
    original_price: 499,
    discount_percentage: 15,
    isbn: '978-0525559474',
    publisher: 'Viking',
    pages: 304,
    language: 'English',
    format: 'hardcover',
    category: mockCategories[0],
    rating: 4.6,
    review_count: 18765,
    is_bestseller: true,
    is_featured: true,
    stock_quantity: 40,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'book-11',
    title: 'Diary of a Wimpy Kid: Hot Mess',
    slug: 'diary-wimpy-kid-hot-mess',
    author: {
      uid: 'author-10',
      title: 'Jeff Kinney',
      name: 'Jeff Kinney',
      slug: 'jeff-kinney',
      bio: 'Jeff Kinney is an American author and cartoonist.',
      created_at: '2024-01-01',
      updated_at: '2024-01-01',
      locale: 'en-us',
    },
    description: 'The latest adventure in the bestselling Diary of a Wimpy Kid series.',
    short_description: 'Book 19 in the beloved series',
    cover_image: {
      uid: 'img-11',
      url: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&h=600&fit=crop',
      filename: 'wimpy-kid-19.jpg',
      content_type: 'image/jpeg',
    },
    price: 339,
    original_price: 399,
    discount_percentage: 15,
    isbn: '978-1419766992',
    publisher: 'Amulet Books',
    pages: 224,
    language: 'English',
    format: 'hardcover',
    category: mockCategories[5],
    age_group: '9-12 Years',
    rating: 4.7,
    review_count: 5432,
    is_new_arrival: true,
    stock_quantity: 50,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'book-12',
    title: 'Think and Grow Rich',
    slug: 'think-and-grow-rich',
    author: {
      uid: 'author-11',
      title: 'Napoleon Hill',
      name: 'Napoleon Hill',
      slug: 'napoleon-hill',
      bio: 'Napoleon Hill was an American self-help author.',
      created_at: '2024-01-01',
      updated_at: '2024-01-01',
      locale: 'en-us',
    },
    description: 'The classic guide to success and wealth that has inspired millions.',
    short_description: 'The timeless classic on success',
    cover_image: {
      uid: 'img-12',
      url: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=400&h=600&fit=crop',
      filename: 'think-grow-rich.jpg',
      content_type: 'image/jpeg',
    },
    price: 199,
    original_price: 250,
    discount_percentage: 20,
    isbn: '978-0449214923',
    publisher: 'Fawcett Books',
    pages: 320,
    language: 'English',
    format: 'paperback',
    category: mockCategories[3],
    rating: 4.5,
    review_count: 32156,
    is_bestseller: true,
    stock_quantity: 45,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
];

export const mockBanners: Banner[] = [
  {
    uid: 'banner-1',
    title: 'New Year Reading Goals',
    subtitle: 'Start 2026 Right',
    description: 'Discover books that will transform your year. Up to 40% off on bestsellers!',
    background_image: {
      uid: 'banner-img-1',
      url: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=1600&h=600&fit=crop',
      filename: 'banner-1.jpg',
      content_type: 'image/jpeg',
    },
    cta_text: 'Shop Now',
    cta_link: '/category/bestsellers',
    text_color: 'light',
    display_order: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'banner-2',
    title: 'Children\'s Book Festival',
    subtitle: 'Adventures Await',
    description: 'Spark imagination with our curated collection of children\'s books. Special discounts inside!',
    background_image: {
      uid: 'banner-img-2',
      url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=1600&h=600&fit=crop',
      filename: 'banner-2.jpg',
      content_type: 'image/jpeg',
    },
    cta_text: 'Explore',
    cta_link: '/category/kids-books',
    text_color: 'light',
    display_order: 2,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
  {
    uid: 'banner-3',
    title: 'Business & Finance Week',
    subtitle: 'Invest in Knowledge',
    description: 'The best business books at unbeatable prices. Free shipping on orders over ₹500!',
    background_image: {
      uid: 'banner-img-3',
      url: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=1600&h=600&fit=crop',
      filename: 'banner-3.jpg',
      content_type: 'image/jpeg',
    },
    cta_text: 'Shop Collection',
    cta_link: '/category/business-finance',
    text_color: 'dark',
    display_order: 3,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    locale: 'en-us',
  },
];

// Helper functions to get mock data
export function getMockBestsellers(): Book[] {
  return mockBooks.filter((book) => book.is_bestseller);
}

export function getMockNewArrivals(): Book[] {
  return mockBooks.filter((book) => book.is_new_arrival);
}

export function getMockFeaturedBooks(): Book[] {
  return mockBooks.filter((book) => book.is_featured);
}

export function getMockKidsBooks(): Book[] {
  return mockBooks.filter((book) => {
    const category = Array.isArray(book.category) ? book.category[0] : book.category;
    return category?.slug === 'kids-books';
  });
}

export function getMockBooksByCategory(categorySlug: string): Book[] {
  return mockBooks.filter((book) => {
    const category = Array.isArray(book.category) ? book.category[0] : book.category;
    return category?.slug === categorySlug;
  });
}

export function getMockBookBySlug(slug: string): Book | undefined {
  return mockBooks.find((book) => book.slug === slug);
}

